### ISSUE TITLE
Teleport Slack Plugin as notification system only

### ISSUE THREAD

**Issue by aelkugia** [gravitational/teleport-plugins#121]
Customer request came in looking for feasibility to only pass a notification via Slack channel when a request comes in and have it only state `pending request`. They still want to have the approve/deny happen via tctl. 

Use case:

Their Slack is managed by their IT so their IT has access to any channel, so basically anyone from IT can request admin role and then go to the Slack channel and approve it themselves.

With the current setup of the Slack plugin 2 concerns were brought up:

1. It potentially allows people to bypass teleport access control via slack
2. You don’t have the possibility to log who actually take the action

**Comment by xnutsive** [comment]
@benarent asked me about this a week ago — my bad for not filing the issue then. 

> 2. You don’t have the possibility to log who actually take the action

With 0.2.0 teleport-slack will log the identity of the user who approved/denied a request to the Teleport's audit log. Howerver, I think the use case and security concerns are valid, and we can address them. 

One way is to add a config option `allow_approvals_on_slack = True`, and if that's switched to false, then the plugin should not show the approval / denial buttons on the slack notification message when a request pops up. 

This change is minimal and I can draft it up in an hour or so. 

However, this would leave the HTTP listener in the plugin intact, i.e. the buttons are not there, but if someone crafts a request to Slack to _look_ like an approval button has been clicked, and if there's no protection from such actions on Slack's side, and if Slack then hits teleport-slack plugin with their webhook — teleport-slack will approve or deny the request. 

To make sure this can't happen at all, we'll need to also not listen to Slack's webhooks at all, since the Slack message will just be a notification and won't be interactive. 

@marshall-lee, do you want to take and solve this this Friday, or is it more complex than I imagine?

**Comment by marshall-lee** [comment]
Hi @aelkugia !

> Their Slack is managed by their IT so their IT has access to any channel

Did you try private channels? According to https://twitter.com/SlackHQ/status/872506889065680896 private channels are not visible even to the owners.

**Comment by aelkugia** [comment]
@marshall-lee I wasn't aware that private channels are not visible to the owners. Thanks for pointing that out.

**Comment by xnutsive** [comment]
I'll reply here since we started the discussion here, instead of the PR (#126). Let's figure out if we actually need this mode, and talk about it's motivation, and keep the pull request discussion to be specifically about code quality and security of the changes I proposed. 

@marshall-lee, I see your point: if the client wanted to only allow certain people _see_ access request notifications on Slack, and _all_ of them can approve the requests — then the private channels make sense. 

Vlad also pointed out that if the client uses public channel for teleport-slack, then virtually anyone on the company can find this channel and join it — and thus get access to approval workflow. Not very secure. FYI @aelkugia. So, overall, using a private channel with a certain subset of Slack users invited makes sense. 

That said, there are two types of situations that the plugin currently doesn't cover: 

1. The client wants a bunch of people to see access request notifications on Slack, but _none_ of them should be able to approve via Slack. If that's the case, then #126 would work fine. 
2. The client wants a bunch of people to see access request notifications on Slack, but only _some of them_ should be able to approve via Slack. Then, #126 won't help, and we need (as @benarent pointed out) to provide a config option to set a list of Slack usernames who can approve/deny requests, and gracefully decline approval/denial from users who are not on that list. 

@aelkugia, @benarent, if you're 100% certain about what kind of process the user wants to run — we can decide if we want to merge #126 in as a solution. If we're unsure, I think it would make sense to see how people use the plugin and then decide. 

If we have to support allow-lists of users on a config level, then we can just use that to do notification-only mode: if an empty list is passed in the config, then no one can accept/deny a request, and then the buttons won't be displayed. 

What path should we go with?

**Comment by aelkugia** [comment]
@xnutsive based on conversations I've had with customers - the first situation is what has been discussed. They would like a Slack channel for notifications, but no one would be able to approve via Slack.

**Comment by webvictim** [comment]
One potential other workaround that @fspmarshall suggested for the “post-to-slack-but-don’t-allow-approval” model that we’re talking about here is to give the teleport-plugins Teleport user/role (that’s created for plugin integration) read permissions, but not write permissions. That way no approval could be sent, even if someone managed to craft the correct webhook/callback.

**Comment by fspmarshall** [comment]
> ...give the teleport-plugins Teleport user/role (...) read permissions, but not write permissions.

More specifically, omit the `update` verb from the standard `['list','read','update']` list that we usually grant plugin users in all the examples.  For users who just care about security but aren't particularly worried about UX, this solution works out of the box.  It just leaves you with useless `approve`/`deny` buttons hanging around.

**Comment by xnutsive** [comment]
@aelkugia, thanks for the clarification! 

@webvictim @fspmarshall, I think setting up the teleport-plugin user to not have the permission to update access requests is secure, compared to just not rendering buttons, or not processing requests in the plugin itself. 

I think we actually should do both: 
- Tell users to setup the teleport-plugin user so that it doesn't have a permission to update requests AND
- Tweak the plugin with a config option to not process approve/deny requests and not show buttons in notification_only mode. 

If we only do the first, but not the second part, then the plugin will error out if someone tries to press the approval button — that won't be transparent and obvious for the users, and we might need to handle that error internally. It's easier to just make sure that doesn't happen in the first place. #126 should do that — I'll just add a readme note about the notification_only mode and about the user setup to it. 

Would that be a good full solution to this?
