### ISSUE TITLE
Teleport event forwarder

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport-plugins#149]
### Feature Request

Fluentd supports mTLS

https://docs.fluentd.org/configuration/transport-section

Customers should be able to:

* Generate a certificate with a purpose fluentd. 
* Connect fluentd to proxy
* Receive cluster events
* Export events and **session recordings** to S3 buckets using Fluentd S3 output https://docs.fluentd.org/v/0.12/output/s3

The plugin should store local checkpoint and use iterator to resume from the last state.

This depends on gravitational/teleport#5435

**Comment by klizhentas** [comment]
I suggest you start with our exsting HTTPS events pagination API while you are waiting forhttps://github.com/gravitational/teleport/issues/5435 so you can familiarize yourself with details on how to write fluentd plugins

**Comment by klizhentas** [comment]
It's an interesting computer science problem as well. You'd have to keep a checkpoint/iterator on the fluentd server plugin side so when it looses a connection it can start replaying events from the last checkpoint. I wonder if you'd need a checkpoint API as well. Your peer from the teleport side is @xacrimon - Joel.

**Comment by gzigzigzeo** [comment]
@klizhentas

fluentd supports TLS, while standard golang binding does not. We are going to need a PR with TLS implementation.

It's still not clear for me where to store cursor (checkpoint/iterator) value. The problem is that we need storage to save it. Simple KVS where key would be fluentd tag name, and value would be the latest cursor value.

1. We could save cursor values in fluentd. fluentd has the ability to store plugin internal states. However, it will involve writing a custom Ruby plugin to save and return cursor values. We want to avoid it. Plus, fluentd storage is temporary by nature, as I get it.

2. We could save cursor values in our fetcher plugin instance. This will make it stateful. So, we'll have to implement and provide different storage options (like, SQL, Redis, whatever user has close to collector instance). 

3. We could implement cursor API on Teleport side. Teleport has storage and it should not be a big problem. It could look like this: collector reads a bunch of records from Teleport, sends them to fluentd and ACKs latest record cursor value after records are received. In case, something goes wrong, it will restart from the latest success value.

Clearly, there could be the problem with duplicated records. However, if we make a cursor sequential, duplicates could be filtered on fluentd side using comparsion-filter plugin (https://github.com/reizist/fluent-plugin-comparison-filter). In case it is not reliable enough, we could calculate hash for every log entry and implement tiny fluentd Ruby plugin which would omit duplicates using hashes of last N records went through.

**Comment by gzigzigzeo** [comment]
Regarding Rust. Standard Rust bindings for fluentd (fruently, log4rs-rust) do not support TLS and retries. If we decide to go with Rust, we will have to reimplement a good half of api/client package (auth methods). This will also require supporting future changes in auth methods for both two languages. WDYT?

**Comment by gzigzigzeo** [comment]
One more thing regarding this. Do we really need to have separate tool for this? Why not to add fluentd logging feature to the Teleport core?

**Comment by klizhentas** [comment]
Re: iterator:

We need an API to store iterator in the database, so Teleport should provide one. Let's ask @xacrimon on what does he think about that.

Regarding Rust, I'm pretty sure there is a way for it to use TLS :) Can you point us to the bindings code and we will take a look.
The point about reimplementing API is valid, but we wanted to implement rust API for Teleport anyways. This could take a lot of time though, can you point us to Go bindings?

We would want fluentd plugin because our customers are using fluentd and it will plugin nicely into their existing infrastructure.

**Comment by gzigzigzeo** [comment]
@klizhentas 

> Regarding Rust, I'm pretty sure there is a way for it to use TLS :)

Sure, I am just saying that it is not supported by the fluentd binding yet :-) Actually, most of the bindings for different languages do not support TLS (

Rust bindings: https://docs.rs/log4rs/1.0.0/log4rs/ - one, https://github.com/cosmo0920/fruently - two. 

Go binding: https://github.com/fluent/fluent-logger-golang (surprisingly not listed in official docs).

> The point about reimplementing API is valid, but we wanted to implement rust API for Teleport anyways. This could take a lot of time though

Yes, it could take some time, and it most likely will :-( 

> We would want fluentd plugin because our customers are using fluentd and it will plugin nicely into their existing infrastructure.

I get it, yes. I am not questioning the need for fluentd. I mean the following: fluentd does not have plugins which consume data from external sources. Fluentd can't go and fetch the records from a server. So, we need a tool which will fetch records from Teleport and send them to fluentd. And my question is: do we really need a separate tool, or would it be more convenient to provide this event-to-fluentd push service within the Teleport itself?

For example, Docker has embedded fluentd log driver. You just specify "docker run --log-driver=fluentd" with some additional config and that's it.

**Comment by gzigzigzeo** [comment]
No. My fault. fluentd has input plugins which could go and fetch logs.

**Comment by xacrimon** [comment]
Since the events pagination API is a pull but fluent needs events pushed I only really see two options.

A) A service which sits inbetween Teleport and fluentd as @gzigzigzeo described.
B) A fluentd push-style log transport within Teleport.

I think we already have support for pushing events to more than one backend within Teleport using our audit log multiplexer type, otherwise it should be trivial to implement. The fluentd support for these data fetch plugins is indeed quite "meh" from experience and not a good nor complete problem solution so that solution is ruled out.

Both options A and B are doable but it seems to be like just a question of how expansive we want to make Teleport core. If we want a slimmer Teleport, option A seems advantageous but option B seems less complicated and clean. 

I don't believe we have a way for plugins to provide audit log backends which means that this currently isn't implementable as a plugin. Personally I don't really have a preference between A or B but I will have to defer to @klizhentas on that.

**Comment by gzigzigzeo** [comment]
> Also explore how to download recorded sessoins and re-upload to another S3 bucket, do we need fluentd plugin for that?

It depends. S3 can replicate two buckets https://aws.amazon.com/premiumsupport/knowledge-center/s3-large-transfer-between-buckets/, it can replicate selectively based on key prefix or object tags (https://docs.aws.amazon.com/AmazonS3/latest/userguide/replication.html).

That's the easiest way. However, it depends on the security settings. Would we be able to grant access to source S3 bucket to an owner of a target bucket?

@klizhentas

**Comment by klizhentas** [comment]
@gzigzigzeo we should not use S3 for this, instead we should rely on audit streamers API to import and re-export events.

**Comment by gzigzigzeo** [comment]
@klizhentas Sorry, I do not get it. I am talking about session recordings which are files on S3, correct? So, the question was if we could move session recording to target S3.

**Comment by klizhentas** [comment]
@gzigzigzeo the fact that the recordings are on S3 is an implementation detail for AWS. It is a different storage on Google Cloud. So instead please use the stream API that is agnostic:

https://github.com/gravitational/teleport/blob/master/lib/events/api.go#L455

It is already built and you can upload streams with checkpoints and resumes. You can't download streams yet, that part is missing and Joel would have to add it. But then your upload/download plugin would just create a download stream and upload stream and io.Copy on those.

**Comment by klizhentas** [comment]
I think we are arriving at the following design:

* Event forwarder is just another Go program that uses Go API of teleport.
* It can follow events and download streams. It will process streams and reupload to target storage, for example S3. It will download events and push to local fluentd

WYT?

**Comment by gzigzigzeo** [comment]
@klizhentas Yes, I agree. Okay.

**Comment by xacrimon** [comment]
@klizhentas Seems like a good solution.

**Comment by benarent** [comment]
The FluentD provider has been published. Follow this guide for more instructions https://goteleport.com/docs/setup/guides/fluentd/
