### ISSUE TITLE
Update permission for upcoming Slack updates. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#22]
https://medium.com/slack-developer-blog/more-precision-less-restrictions-a3550006f9c3

**Comment by xnutsive** [comment]
This will only affect the user setup guide, as far as I see. Yes, the scope names will change in the guide, but we won't be affected by any restrictions they apply to App Directory since Slackbot won't be listed, and people will just  create a new Slack app for it and deploy it to their Slack Workspace.

**Comment by xnutsive** [comment]
This is addressed in #46, I'll close this once I make new screenshots for the guide.

**Comment by xnutsive** [comment]
Closing this, since if any changes will be necessary for the end-users apps, we'll just describe them in the docs. Referring to the docs issue: #7.
