### ISSUE TITLE
Drift in times causes log spam

### ISSUE THREAD

**Issue by klizhentas** [gravitational/teleport-plugins#222]
# teleport_role.example will be updated in-place
  ~ resource "teleport_role" "example" {
        id      = "example"
        # (2 unchanged attributes hidden)

      ~ metadata {
          ~ expires     = "2022-10-12T07:20:50Z" -> "2022-10-12T07:20:50.52Z"
            name        = "example"
            # (3 unchanged attributes hidden)
        }

        # (1 unchanged block hidden)
    }

**Comment by gzigzigzeo** [comment]
1. Time with microseconds part (.5) is a valid time from Terraform point of view. So, microseconds can be specified.
2. Microseconds work okay with Token. `expires = "2022-10-12T07:20:51.51Z"` does not trigger state drift.
3. It fails with users and roles, on cloud only.

My guess is that for users and roles, microseconds are omitted on Teleport side. State drift appears when Terraform reads object from Teleport after create and it comes back without microseconds. I guess, that is because of the storage settings: locally everything works fine.

I think, we need to leave everything as is for now. I could provide custom validation function which will block microseconds for appropriate fields. To do it I need to know which time fields does not support microseconds on Teleport side.

**Comment by gzigzigzeo** [comment]
This one is fixed by introducing custom compare fn

**Comment by gzigzigzeo** [comment]
This is done & merged.
