### ISSUE TITLE
Error: failed to delete role that still in use by a user. - Unclear message

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#283]
While destroying a TF stack, I have the above error message. It's isn't clear what the next steps are and which role is causing the issue.

```
│
│ Error: failed to delete role that still in use by a user. Check system server logs for more details.
│
│
```

**Comment by gzigzigzeo** [comment]
@benarent Could you please provide your user and role configuration? The error itself is generated on the Terraform side, but I think that I could enrich it with the name of the role in question. Just need little bit more details to reproduce. The next steps would be to revoke this role from a users using it before next attempt, but, unfortunately, we can't print user names here because of security restrictions.
