### ISSUE TITLE
Error: Resource instance managed by newer provider version

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#536]
While upgrading to the new Terraform provider I was met with this message. 

```
╷
│ Error: Resource instance managed by newer provider version
│
│ The current state of teleport_user.access-plugin-slack was created by a newer provider version than is currently selected. Upgrade the teleport provider to work with this
│ state.
╵
```
I fixed this by using `terraform state replace-provider`.

```
terraform state replace-provider gravitational.com/teleport/teleport terraform.releases.teleport.dev/gravitational/teleport
```

After this I had to backed up and deleted  `.terraform.lock.hcl`

```
terraform init
terraform plan
```

After this, I did still need to delete some old resources. I did this using `terraform state rm` and then everything worked out.

**Comment by marcoandredinis** [comment]
I did some tests and it seems it was caused by the upgrade on our underlying lib
We are now using the recommended library from Terraform and should not need to go through this anytime soon.

I did some tests, and was able to upgrade from 9.0.4 to multiple 9.x versions

Please let me know if you happen to hit an error migrating 9.x -> 9.y (or 10.z in the future :sweat_smile: )

**Comment by highb** [comment]
I also encountered this, but I skipped directly to 10.2.6 from 8.x, since both 9 and 10 were equally broken upgrades and I was dumping all the state anyway. 🤷 

# Steps taken for upgrade
1. Removing all of the existing state
2. Update the provider to 10.2.6
3. Re-import everything by auto generating and reviewing an import script from the TF plan with this command:
`tf show -json plan.tfplan | jq -r '.resource_changes | .[] | select(.change.actions[0] == "create") | (.address | @sh) + " " + .[change.after.metadata.name](http://change.after.metadata.name/) | @sh' | xargs -n 1 echo terraform import > import-remainder.sh`
4. After reviewing and running the import script, I was able to fix up the remaining changes on the provider (blocks to maps in a lot of places, mostly) 
5. TF plan and apply runs cleanly
