### ISSUE TITLE
Event handler should reread certificates when updated

### ISSUE THREAD

**Issue by webvictim** [gravitational/teleport-plugins#641]
One great use case for Machine ID is for the event handler/exporter plugin to use its auto-refreshing credentials to read and forward Teleport's audit logs in a secure way (without needing a long-lived identity file)

At the moment, I don't believe this is possible as the plugin only reads its credentials on startup. It'd be better if it watched the directory and reloaded the credentials gracefully whenever they're updated. This is even true for non-machine ID credentials to make the service more resilient.

**Comment by hugoShaka** [comment]
While we can add this in all the plugins, it would be great also to have tbot either execute a command on reload (e.g. sending a signal or restarting a daemon) or have tbot run our process, like [consul-agent exec mode](https://github.com/hashicorp/consul-template/blob/main/docs/configuration.md#exec-mode).

cc @strideynet

**Comment by strideynet** [comment]
My personal view is we can probably quite easily achieve this via sending a signal etc from `tbot` and this does avoid implementing this as a watcher within event handler - I'll look into the restrictions around this and determine if this is a route we can take. I think I'd rather send a signal than supervise the process as I think ultimately tools like `systemd` etc are much better suited to supervision than anything we could build out for this.

Another option that comes to mind, is potentially embedding Machine ID within event handler. Whilst a bit more heavy weight, I do wonder if something like this would offer a better user experience, however, I'm not sure if that improvement is worth the additional engineering effort and complexity that would present.

**Comment by strideynet** [comment]
My opinion is that we should modify the plugins to support watching the identity file input and automatically reloading when this file updates.

I briefly considered driving this via `tbot` sending a signal, but rejected this, as this would not work nicely where `tbot` is outputting credentials to a secret in Kubernetes or similar. Watching the filesystem for updates will work nicely with cases where the plugin is running as a Pod in Kubernetes with the identity file mounted as a secret, and in most other circumstances.

I will focus on implementing this watching behaviour for identity files over the separate TLS cert/key/CAs, as this poses a challenge in that the all files will not be updated atomically during a certificate renewal. This introduces some interesting failure states which are not a concern when using the singular identity file.

**Comment by strideynet** [comment]
Having considered this for some time, I believe that the best implementation here would be for all the plugins to support setting up a file watcher against a configured identity file input rather than a model where `tbot` supervises the process for the following reasons:
- `tbot` does not provide the stability guarantees or configurability of tooling like Kubernetes or SystemD.
- This model does not work nicely for situations where users may want a single `tbot` to provide credentials to multiple plugins.
- File watching works with Kubernetes Secrets volume mounting, which will be a supported destination of tbot in future. This provides a nice experience for running `tbot` and a Teleport plugin in the same cluster.
- By empowering the plugin to handle this, smarter decisions can be made about how to handle in-flight events.
- This also works nicely for situations where the user is not using `tbot` but wants to rotate credentials.
- An implementation which is based on file watching can easily be modified to also support reloading these credentials on a signal.
- Designing this implementation correctly will open the door to allowing plugins to directly join the cluster using Machine ID rather than a seperate `tbot` daemon 😇 

This file watching is most likely to be supported for identity files and not supported TLS certificates and keys, this is because a renewal will atomically update the identity file, but this same atomicity cannot be applied to multiple files.

**Comment by strideynet** [comment]
Related to https://github.com/gravitational/teleport/issues/23341
