### ISSUE TITLE
Pagerduty discussion: should we do the auto-approve flow?

### ISSUE THREAD

**Issue by xnutsive** [gravitational/teleport-plugins#72]
As of right now, Pagerduty integration allows to manually approve or deny Teleport permission requests. 

@Ben proposed implementing an auto-approve flow for situations when an on-call engineer requests the permission themselves. This behavior would be opt-in on a config level.

**Here's how the flow should work**

- A user runs `tsh login --request-roles %roles%`
- Teleport broadcasts the request via the GRPC API. 
- `teleport-pagerduty` plugin uses the User ID provided in `access.Request.User`
- `teleport-pagerduty` uses [Schedules API](https://api-reference.pagerduty.com/#!/Schedules/get_schedules) to determine the list of Pagerduty Users who are on call. 
- `teleport-pagerduty` uses `Request.User` to match against Pagerduty users. If the request user matches the user on call, and if they're the only on call user, then `teleport-pagerduty` immediately approves the request, automatically. 

**We need several decisions before we can implement this flow:** 

1. Should the request be automatically approved only if the requester is _the only_ user who's on call, or if the requester is _one of the users on call_? I.e. if there's someone else on call who can review their request, should we still auto-approve? Should this be optional?
2. On my local VM, I'm getting my Linux username as `Request.User` for my permission requests. To match Teleport cluster users to Pagerduty users, we'll either need to match their emails, or other metadata that can be stored in both systems. Pagerduty alllows “contact methods” that we can use, but that approach feels.. unreliable. 
3. When auto-approve occurs, should the plugin still create an incident and auto-resolve it to live a log / trace that a certain permission request was created and auto-approved, or leave it completely out of Pagerduty? 

**Engineering considerations** 

Whatever way we choose to match teleport user to pagerduty users, Pagerduty's Schedule API will only return a bunch of _user IDs_. So unless we store them in Teleport and provide them in Request.PagerdutyUserID, the plugin will need to iterate over all of the schedules that are current, and grab all users one by one, and then match their information to teleport's user info. That's O(n) API requests just to search for a matching user record, N is the count of users on call. Might as well do /users/all and cache the results in the plugin at start time and update it from time to time. 

**Next steps** 
Let's first discuss the desired behavior and decide on urgency / priority of this behavior. I'll update the issue with the spec once we have that. We'll then schedule the implementation ;)

**Comment by benarent** [comment]
We've had some more feedback for this plugin, I've attached the reply to the specific questions here. 

1. I think the best options would be map PD schedule IDs to Teleport roles. For example, I'm oncall in PD schedule called Teleport(ID XXXXXX) . I'm requesting Teleport-admin role and I can get it if I'm oncall in schedule XXXXX.
But if I'm oncall in schedule Email-Service(ID YYYYYY) and I'm trying to get role Teleport-admin this request should be denied.
The requests should be auto approved. If we want approval by a person we can use incident for this.

It doesn't matter how many people are oncall at the moment. They all should be able to get additional roles if they are oncall in the correct PD schedule. 

2. As I mentioned during the meeting it could be solved by adding an additional Okta trait to Teleport user(email). This way it would be pretty straightforward to map users. This approach needs some code change in the plugin, because the current implementation of Client.GetUser function returns limited number of attributes(it doesn't return traits

3. I don't think we should rely on PagerDuty here. The requests must be logged on the server running the plugin

**Comment by marshall-lee** [comment]
@benarent As for **2.** I cannot find that it's possible to fetch Okta trait using PagerDuty API. Also I think that pagerduty plugin must be generic enough so it should work well even when no SSO provider is used at all.

So I still prefer to stick with a previous idea of mapping `pagerduty_user_id <-> teleport_user`.

cc @xnutsive

**Comment by benarent** [comment]
I was thinking we get it passed from Teleport as part of the access request? Have you tried setting up Okta -> Making the request?  '{{external.pd_user_id}}'

You don't even need the traits, if Okta is setup it'll always use email. 

```
> Profile URL:  https://teleport-ent-4-3.practice.io:3080
  Logged in as: ops@gravitational.io
  Cluster:      teleport5auth
  Roles:        admin, dba*
  Traits:       groups: [Everyone okta-admin okta-dev]
```

**Comment by xnutsive** [comment]
Sounds like we'll need a test stand with Teleport and Okta setup, along with an Okta developer account, to see how / if it works. @benarent, I think you mentioned you have one?

**Comment by benarent** [comment]
I think I looped back in Slack, but it's possible to signup via https://developer.okta.com/

**Comment by benarent** [comment]
@marshall-lee @xnutsive Have we made any progress on this workflow? Any open questions? 

If needed I can create the accounts needed.
