### ISSUE TITLE
Containerised builds for testing

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#81]
Follow https://github.com/gravitational/teleport/tree/master/docker#docker as an example to help with development and testing.

**Comment by xnutsive** [comment]
Drafting my plan on this. 

1. Create a `docker` directory in the repo root for this, with a `readme.md` and a `Makefile`in there. 

2. Document that this builds on Teleport's containerised builds, and use that as the foundation. Assume we have the Teleport's docker test clusters. 

3. In Makefile, provide a generic `up` and `down` that start a teleport cluster that is similar, but separate from Teleport's `one`and `two`clusters, and all of the available integrations in their own containers for each plugin. 

4. Provide `make slack-up / make slack-down` to control specific integrations. 

5. Provide a way to define toml / yaml configs that will be passed to the plugins. 

I'll tag you once this is ready, want to wrap it up this week.

**Comment by xnutsive** [comment]
Update on this: since there are multiple recent tickets re: Pagerduty plugins, I'll continue working on this. 

To get this merged in and ready for internal usage, I want to do a few things: 

1. Make sure that the flow actually works if a user just pastes commands from the README one by one into their terminal, assuming they have docker and Make installed locally. 

2. Add Pagerduty to the flow. Easy. 

3. Add a way to store plugin configs, including sensitive information like external OAuth apps client_ids and secrets, in a vault / encrypted way, so that we can all share a key file to it, but the sample configs can be in the repo or easily accessible. This is a required step to make testing easy. Without it, you'd first need to provision a new Slack app for example, to test teleport-slack, and setup it's permissions, webhook URLs, etc. 

Once that is ready, we can run full end to end tests using any CI that can spin up Docker VMs ;)
