### ISSUE TITLE
Teleport PagerDuty plugin hangs if PD user 'resolves' ticket without action. 

### ISSUE THREAD

**Issue by benarent** [gravitational/teleport-plugins#87]
While testings I was able to resolve a ticket, but since I didn't perform any action the incident is still open. 

```log
INFO   PagerDuty incident created incident_id:P44JOAR pagerduty/main.go:393
```

![image](https://user-images.githubusercontent.com/559288/82609985-759caa80-9b72-11ea-9d40-0d541d7828ed.png)

If the issue is Resolved in the PD UI, it should tell the end user that their request has been denied.

**Comment by marshall-lee** [comment]
@benarent 

So you think we should deny teleport access requests when resolving the incident?

I thought we shouldn't do anything with the request if the user didn't choose any of the deny/approve actions. What if user wants neither to aprove nor to deny the request but just resolve the incident? It's the "third" option that I think should be available to the user.

**Comment by xnutsive** [comment]
@marshall-lee reviewing this now. 

For the user who receives the request, they might want to do nothing and ignore the request, that's valid. But for the user who _requested access_, that would mean that their request is _not approved_.\

@benarent, if the associated incident is closed (without declining explicitly) in PD, someone else could still approve this request in tctl, right? Are you sure you want teleport-pagerduty to decline the request if the associated incident gets resolved without an explicit action? 

My concern with this is since two people directly involved in the work on the plugin had two different opinions, and since this behavior won't be explicit (i.e. closing an incident doesn't imply the underlying request will be closed or user will be notified in any way) — this might cause more confusion along the way for end users. 

In any case, I think it'd be worth adding a note to the documentation about this behavior, whatever way we choose it should work. 

@benarent what do you think?
